# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    npm install
  displayName: 'installing node modules'

- script: npm run build
  displayName: 'creating build'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Save artifacts to refer them in release builds
- task: PublishPipelineArtifact@1
  inputs:
    path: build/
    artifact: react-hooks-build